# Generated by Django 4.2.6 on 2023-11-29 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_useraccount_email_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.CharField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
