# Generated by Django 4.2.6 on 2023-11-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.CharField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
