# Generated by Django 4.2.6 on 2023-11-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_useraccount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='EID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
