# Generated by Django 4.2.6 on 2023-12-06 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_useraccount_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='EID',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('proctor', 'Proctor'), ('admin', 'Admin')], max_length=10),
        ),
    ]
