# Generated by Django 4.2.6 on 2023-12-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_useraccount_eid_alter_useraccount_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('proctor', 'Proctor')], max_length=10),
        ),
    ]
