# Generated by Django 4.2.6 on 2023-12-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_useraccount_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='EID',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
