# Generated by Django 4.2.6 on 2023-12-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_useraccount_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('proctor', 'Proctor'), ('admin', 'Admin')], max_length=10),
        ),
    ]
