# Generated by Django 4.2.6 on 2024-01-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_useraccount_eid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('BranchID', models.AutoField(primary_key=True, serialize=False)),
                ('BranchName', models.CharField(max_length=255)),
                ('ClassName', models.CharField(max_length=255)),
            ],
        ),
    ]
