# Generated by Django 4.2.6 on 2024-01-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_proctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proctor',
            old_name='ClassID',
            new_name='BranchID',
        ),
        migrations.RenameField(
            model_name='proctor',
            old_name='UserID',
            new_name='id',
        ),
        migrations.AlterUniqueTogether(
            name='proctor',
            unique_together={('id', 'BranchID')},
        ),
    ]
