# Generated by Django 4.2.6 on 2024-01-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_subjects_student_facultyteachingassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='Subjectcode',
            field=models.CharField(default=101, max_length=255),
            preserve_default=False,
        ),
    ]
