# Generated by Django 4.2.6 on 2024-01-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_subjects_subjectcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='BranchName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='BranchName',
            field=models.CharField(max_length=255),
        ),
    ]
