# Generated by Django 4.2.6 on 2024-01-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_branch_branchname_alter_subjects_branchname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='BranchName',
            field=models.CharField(max_length=255),
        ),
    ]
