# Generated by Django 4.2.6 on 2024-02-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_branch_branchname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyteachingassignment',
            name='room',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='proctor',
            name='SemesterNumber',
            field=models.IntegerField(max_length=255),
        ),
    ]
