# Generated by Django 4.2.6 on 2024-03-08 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_facultyteachingassignment_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='LecturesAttended',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='TotalLectures',
        ),
        migrations.RemoveField(
            model_name='facultyteachingassignment',
            name='BranchID',
        ),
        migrations.AddField(
            model_name='facultyteachingassignment',
            name='Class',
            field=models.CharField(default=False),
        ),
        migrations.AlterField(
            model_name='proctor',
            name='SemesterNumber',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='StudentSubjectAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lectures', models.IntegerField(default=0)),
                ('attended_lectures', models.IntegerField(default=0)),
                ('EnrollmentNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('loginId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=255)),
                ('BranchName', models.CharField(max_length=255)),
                ('loginTime', models.DateTimeField()),
                ('attendanceTime', models.DateTimeField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(through='api.StudentSubjectAttendance', to='api.subjects'),
        ),
    ]
