# Generated by Django 4.2.6 on 2024-03-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_attendance_lecturesattended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='EnrollmentNumber',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
