# Generated by Django 4.2.6 on 2024-03-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_student_enrollmentnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='login',
            name='attendanceTime',
            field=models.DateTimeField(null=True),
        ),
    ]
