# Generated by Django 4.2.6 on 2024-03-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_student_subjects_alter_login_attendancetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='EnrollmentNumber',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='Group',
            field=models.CharField(),
        ),
    ]
