# Generated by Django 4.2.6 on 2024-03-26 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
