# Generated by Django 4.2.6 on 2024-04-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_student_semesternumber_student_totalattended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyteachingassignment',
            name='Class',
            field=models.CharField(),
        ),
    ]
