# Generated by Django 4.2.6 on 2024-05-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_facultyteachingassignment_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='SubjectType',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab'), ('tutorial', 'Tutorial')]),
        ),
    ]
