# Generated by Django 4.2.6 on 2024-06-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_studentsubjectattendance_subjectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attended_lectures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_lectures',
            field=models.IntegerField(default=0),
        ),
    ]
