# Generated by Django 4.2.6 on 2024-07-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_attendance_attended_lectures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='SubjectType',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Lab'), ('tutorial', 'Tutorial')]),
        ),
    ]
