# Generated by Django 4.2.6 on 2024-07-19 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_subjects_subjecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectattendance',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
