# Generated by Django 4.2.6 on 2024-08-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_studentsubjectattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='SubjectType',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab'), ('Tutorial', 'Tutorial')]),
        ),
    ]
