# Generated by Django 4.2.6 on 2024-08-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_subjects_subjecttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='room',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='facultyteachingassignment',
            name='Class',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='facultyteachingassignment',
            name='room',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Group',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='SubjectType',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab'), ('Tutorial', 'Tutorial')], max_length=255),
        ),
    ]
