# Generated by Django 4.2.6 on 2024-03-31 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0029_student_semesternumber_student_totalattended_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendanceDetails',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('EnrollmentNumber', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('Class', models.CharField(default=False)),
                ('year', models.IntegerField()),
                ('room', models.CharField()),
                ('lessThanPercentage', models.FloatField(default=0.0)),
                ('greaterThanPercentage', models.FloatField(default=0.0)),
                ('group', models.CharField()),
                ('SubjectType', models.IntegerField(choices=[('lecture', 'Lecture'), ('lab', 'Lab'), ('tutorial', 'Tutorial')])),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjects')),
            ],
        ),
    ]
