# Generated by Django 4.2.6 on 2024-08-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_alter_studentattendancedetails_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendancedetails',
            name='Class',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentattendancedetails',
            name='group',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentattendancedetails',
            name='room',
            field=models.CharField(default='', max_length=255),
        ),
    ]
